export const tasksDefault = {
    coords: { x: 0, y: 0 },
    tasks: [
        {
            "id": 1,
            "title": "Start last task today",
            "x": 0,
            "y": 0,
            "drag": false,
            "relation": 3,
            "selected": false,
            "active": true,
            "show": true,
            "date": '19.09.2022',
        },
        {
            "id": 2,
            "title": "Complete task #4789",
            "x": 200,
            "y": 200,
            "drag": false,
            "relation": 1,
            "selected": false,
            "active": true,
            "show": true,
            "date": '19.09.2022',
        },
        {
            "id": 3,
            "title": "Complete task #4789",
            "x": 400,
            "y": 400,
            "drag": false,
            "relation": 2,
            "selected": false,
            "active": true,
            "show": true,
            "date": '18.09.2022',
        },
    ],
};